import turtle
t=turtle.Pen()
turtle.bgcolor('white')
t.color('red','yellow')
t.pencolor('yellow')
t.width(4)
t.forward(200)
t.left(90)
t.pencolor('blue')
t.forward(150)
t.left(90)
t.pencolor('red')
t.forward(200)
t.left(90)
t.pencolor('orange')
t.forward(150)
key=input("Press enter to continue....")
