import turtle
t=turtle.Pen()
turtle.bgcolor('white')
t.color('red','yellow')
t.pencolor('yellow')
t.width(5)
t.forward(90)
t.left(90)
t.pencolor('red')
t.forward(90)
turtle.bgcolor('black')
t.color('red','yellow')
t.pencolor('yellow')
t.width(5)
t.left(90)
t.pencolor('red')
t.forward(90)
t.left(90)
t.forward(90)
key=input("Press enter to continue....")
