print ("\nRectangle Calclulations:")
print ("========================")
w = input("Enter width(w): ")
l = input("Enter length(l): ")
a = int(w) * int(l)
p = int(w) + int(l) + int(w) + int(l)
print ("Area is: ", a)
print ("Perimiter is: ", p)
print ()
